export { ChatBot } from './bot/bot.component'
export { BaseComponent } from './base/index'
export { BannerComponent } from './banner/index'
export { QrCodeComponent } from './base/index'
export { TabBarButton, TabBarMore } from './tabBar/index'