export { HomeScreen } from './homeScreen/index'
export { PerfilScreen } from './perfilScreen/index'
export { DiscountScreen } from './discountScreen/index'
export { BotScreen } from './botScreen/index'
export { ScanScreen } from './scanScreen/index'
