export { HomeScreen } from './homeScreen/index'
export { DetailScreen } from './detailScreen/index'
export { PerfilScreen } from './perfilScreen/index'
export { SearchScreen } from './searchScreen/index'
export { BotScreen } from './botScreen/index'
